spring:
  aop:
    auto: true
    proxy-target-class: true
  redis:
    host: 47.92.101.6
    password: dnc.2009
    database: 10
  datasource:
    name: dataSource
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.100.12.20:4506/xzsdcs?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    druid:
      initialSize: 1
      minIdle: 1
      maxActive: 20
      maxWait: 60000
      validationQuery: select 'x' from dual
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      filters: stat,slf4j
mybatis:
  mapper-locations: classpath:mybatis/mapper/**/*Mapper.xml
  config-location: classpath:mybatis/mybatis-config.xml
security:
  oauth2:
    resource:
      filter-order: 3
sc:
  security:
    login:
#      限制用户登录用户名或密码错误次数
      max-fail:
#      是否开启
        enabled: true
#        时长，单位为分钟
        interval: 5
#        错误次数
        times-before-lock: 5
    oauth2:
      browser:
        client-id: webapp
        client-secret: webapp
        grant-type: password
        scope: all
    validate-code:
      image:
        expire-in: 180
        height: 40
        width: 200
        count: 4
  cloud:
    task:
      core-pool-size: 20
      max-pool-size: 50
      queue-capacity: 200
      keep-alive-seconds: 3000
      thread-name-prefix: sc-task-executor-


